### ISSUE TITLE
Move rego utilities to regolibrary

### ISSUE THREAD

**Issue by shm12** [kubescape/opa-utils#6]
Currently, some common rego modules (like `cautils`), are [loaded directly](https://github.com/armosec/opa-utils/blob/d27a3cae792465f4e3152811ab93fcbac880bba1/resources/resourcesutils.go#L110) from [global string variables](https://github.com/armosec/opa-utils/blob/46cc042d38eea5c8ec9bc072fd9a8b5f5fc77142/resources/dependencies.go) .

It seems to me that it make two problems:
1. The rego modules themselves are harder to read and write.
2. The rego policies inside regolibrary depend on these global variables.

I suggest to move these variables to saparet files within regolibrary, and load them from there (using [LoadRegoFiles](https://github.com/armosec/opa-utils/blob/d27a3cae792465f4e3152811ab93fcbac880bba1/resources/resourcesutils.go#L89) , or a function like that)

**Comment by SD-13** [comment]
Hi @shm12, Can I give it a try?

**Comment by shm12** [comment]
Unfortunately, I won't have the time in the near future

**Comment by dwertent** [comment]
Done
