### ISSUE TITLE
Proposal: enforce minimal linting rules

### ISSUE THREAD

**Issue by fredbi** [kubescape/opa-utils#77]
I propose to follow the basic principles that were adopted for github.com/kubescape/kubescape and introduce minimal code standards to this repository.

See my PR proposal: #76 

NOTE: I now realize that most of the impact here concerns the regostore, which has now migrated to github.com/kubescape/regolibrary. Since that one remains for now a plain copy of this repo, I'll propose similar improvements there.

cc: @matthyx @dwertent @vladklokun

**Comment by dwertent** [comment]
Thanks. Yes, we are moving the package to the regolibrary.

/cc @kooomix please take a look into this

**Comment by kooomix** [comment]
Thanks for the proposal, I'll look into it.

**Comment by fredbi** [comment]
@kooomix   @dwertent  I am going to sync the new rego library with the same linting proposal shortly today

**Comment by fredbi** [comment]
@kooomix  @dwertent  this is here: https://github.com/kubescape/regolibrary/pull/299
I've limited the scope to gitregostore for now, for clarity.

**Comment by kooomix** [comment]
@fredbi thats great, so can I delete gitregostore from opautils?

**Comment by fredbi** [comment]
@kooomix at least you shouldn't be blocked by my pending PR #76  any longer. I'll rebase that one after your move and keep just what pertains to opa-utils. Cheers.
