### ISSUE TITLE
Bug: race conditions with regostore get methods

### ISSUE THREAD

**Issue by fredbi** [kubescape/opa-utils#79]
Topic: insufficient locking when accessing the regostore concurrently
Demo: PR #78 

This is annoying if we are using this lib in a concurrent context (e.g. some API server, or if we introduce concurrency in kubescape).

## Issue #1
If I understand the GitRegostore correctly, there is a pattern to lazy-load the controls in a framework and the rules in a control.
The issue is that RLock is then not sufficient to guard such mutating objects when accessed concurrently.

PR #78 introduces some degree of parallel access by slightly altering the existing unit tests. The modified test now exhibits data race when run with "go test -race" (the original test used to produce a sequence of access that did not produce any concurrency on the critical parts).

Proposed solutions:
* pessimistic locking: we could just use the exclusive Lock/Unlock to guard methods that call a lazy-loader: GetOPAControlByName, GetOPAControlByID, GetOPAControlByFrameworkNameAndControlName(), GetOPAControls(), GetOPAFrameworks(), GetOPAFrameworkByName()
=> X-locking on Get methods is difficult to accept...

* dropping the lazy-loading approach: construct the entire object in the setObjects() method, remove lazy-loaders
=> I am not sure we cover all use cases this way / possibly a lot of allocated controls & rules which will never be consumed

* adopting lock-escalation: introduce another set of locks to guard the inner structures only when the mutation actually occurs
=> we need new mutexes to be declared (it is not possible to escalate a R-Lock currently held into X-lock). Beware of deadlocking patterns.

## Issue #2 
There is a race condition on the regexp initialization in func "isControlID"

This is easily guarded by a sync.Once initializer. Alternatively, we could just initialize this eagerly with some "func init()" package initializer.
See PR #78.

cc: @matthyx @dwertent @vladklokun

**Comment by matthyx** [comment]
We've just been busy 3 days of quarterly planning... I promise tomorrow I'll have time to review all your PRs

**Comment by fredbi** [comment]
No worries @matthyx I know how startups work... :)

**Comment by dwertent** [comment]
@fredbi , we are reviewing your lates PRs so we can merge them. 
Thank you!

/cc @YiscahLevySilas1

**Comment by fredbi** [comment]
Note to reviewers:
* PR #78  demonstrates the issue, with a modification of the unit tests
* PR #79 (built on top of #78) proposes a fix, based on the lock escalation method suggested above (there are other possible designs, of course)
