### ISSUE TITLE
Questions re score calculation

### ISSUE THREAD

**Issue by fredbi** [kubescape/opa-utils#89]
I'd like to understand better how the risk score is computed.

I started by beefing up the tests (#87), to get a better grasp of the data structures.
Then I started some clarification & documentation work (#88), at least now I understand what this does.

I could see a few itching issues, which beg some questions:

1. I don't understand why the ScoreUtil is a package-level singleton. I've fixed the data race, but it really feels like we should not do that.
2. I've noticed a difference in the score computed with models V1 and V2. Simulating equivalent situations with both versions of our object model, weights do not follow the same rule. I am wondering if this was desired in the first place. (essentially, passed controls don't add-up to the wcs the same way)
3. Supporting packages with multiple versions is a pain. I don't know if V1 is here to stay for a while. If it is, I could dedicate a little extra time to refactoring how we should define structs with such variants. The current way tends to obfuscate the intent.
4. I could only find one single use case for this package in kubescape: only 1 single method is called (for V2). I think we should reduce the exposed interface to that one and (if possible) deprecate support for V1.

**Comment by fredbi** [comment]
cc: @matthyx @dwertent

**Comment by fredbi** [comment]
@dwertent I can't help sensing the scent of bugs down here with score computation...
Could you please provide some piece of advice re (i) the weird singleton (ii) the discrete, yet real, difference in computations v1 vs v2?

**Comment by matthyx** [comment]
cc @YiscahLevySilas1 I think this code has (or is being) rewritten?

**Comment by YiscahLevySilas1** [comment]
> cc @YiscahLevySilas1 I think this code has (or is being) rewritten?

@fredbi @matthyx Yes, the computation itself is changing, you can see [here](https://github.com/kubescape/opa-utils/blob/7e1278579ab16fd631112975caf24c924c440817/score/score.go#L354) how we will calculate the new score.

**Comment by dwertent** [comment]
Done :)
